allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@mastra/core@1.70.0'
  - '@mastra/deployer@1.70.0'
  - '@mastra/duckdb@1.11.0'
  - '@mastra/libsql@1.23.2'
  - '@mastra/memory@1.32.0'
  - '@mastra/server@1.70.0'
  - mastra@1.31.2
